 name: mvdemo
 channels:
   - defaults
   - conda-forge
 dependencies:
   - python=3
   - pip
   - six
   - pyyaml
   - jinja2
   - scikit-image
     # Uncomment these if you want to analyze a movie file.
     #- ffmpeg
     #- av
     #- moviepy
     # Uncomment if you want the latest stable releases of trackpy and pims, instead
     #- trackpy
     #- pims
   - numba
   - scipy
   - pandas
   - matplotlib
   - ipyparallel
     # Install development versions of trackpy and pims, for compatibility with latest
     # dependencies.
   - pip:
       - git+git://github.com/soft-matter/pims.git#egg=pims
       - git+git://github.com/soft-matter/trackpy.git#egg=trackpy
